### ISSUE TITLE
About sparse gt when eval.py

### ISSUE THREAD

**Issue by mwdotzom** [XiangMochu/MDEUncertainty#3]
Hi Mochu, how is gt being processed in evaluation? I was expecting that the sparse lidar measurements should be interpolated or masked, so that dense prediction has its target to compare with on every pixel. However, I believed I checked eval.py and relevant kitti_data.py, and the sparse gt is being calculated directly.

Here's a brief visualization of error (pred - gt) for `Vit_Sim_Lin_L-1_Sft_Eur_kitti` prediction and `f_gt=PIL.Image.open(gt.png), gt = np.array(f_gt, dtype='float16') / 1000.0`. The spikes underneath(z≈0) is the valid area and the remaining shape is where there's no lidar measurement.
![pred - gt](https://github.com/XiangMochu/MDEUncertainty/assets/55407141/f748edab-906e-47d0-9301-ef73cc820bf8)

**Comment by XiangMochu** [comment]
Invalid values in ground truth(depth=0) are excluded in evaluation, but you can visualize them using any interpolation methods.
